# Generated by Django 5.2.6 on 2025-12-05 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abilities", models.TextField(blank=True)),
                ("moves", models.TextField(blank=True)),
                ("gen_id", models.IntegerField(unique=True)),
                ("main_region", models.CharField(max_length=200)),
                ("internal_name", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("types", models.TextField(blank=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="pokemon_generations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["gen_id"],
            },
        ),
    ]
