# Generated by Django 5.2.6 on 2025-11-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generation",
            name="gen_id",
        ),
    ]
