# Generated by Django 5.2.6 on 2025-11-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("generations", "0001_initial"),
        ("moves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("type_id", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "move_damage_class",
                    models.CharField(
                        blank=True,
                        help_text="The class of damage inflicted by this type (physical, special, etc.).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="types",
                        to="generations.generation",
                    ),
                ),
                (
                    "moves",
                    models.ManyToManyField(
                        blank=True, related_name="move_types", to="moves.pokemonability"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "double_damage_from",
                    models.ManyToManyField(
                        blank=True,
                        related_name="double_damage_to_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "double_damage_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="double_damage_from_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "half_damage_from",
                    models.ManyToManyField(
                        blank=True,
                        related_name="half_damage_to_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "half_damage_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="half_damage_from_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "no_damage_from",
                    models.ManyToManyField(
                        blank=True,
                        related_name="no_damage_to_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "no_damage_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="no_damage_from_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
                (
                    "type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
            ],
        ),
    ]
