# Generated by Django 5.2.6 on 2025-11-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("type_id", models.IntegerField()),
                ("generation", models.CharField(max_length=50, null=True)),
                (
                    "move_damage_class",
                    models.CharField(
                        blank=True,
                        help_text="The class of damage inflicted by this type (physical, special, etc.).",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("moves", models.TextField(null=True)),
            ],
            options={
                "ordering": ["type_id"],
            },
        ),
        migrations.CreateModel(
            name="TypeDamageRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_damage_to", models.TextField(blank=True)),
                ("half_damage_to", models.TextField(blank=True)),
                ("double_damage_to", models.TextField(blank=True)),
                ("no_damage_from", models.TextField(blank=True)),
                ("half_damage_from", models.TextField(blank=True)),
                ("double_damage_from", models.TextField(blank=True)),
                (
                    "type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_relations",
                        to="poke_types.pokemontype",
                    ),
                ),
            ],
        ),
    ]
