# Generated by Django 5.2.6 on 2025-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poke_types", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemontype",
            name="description",
        ),
        migrations.AlterField(
            model_name="pokemontype",
            name="generation",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="double_damage_from",
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="double_damage_to",
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="half_damage_from",
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="half_damage_to",
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="no_damage_from",
        ),
        migrations.RemoveField(
            model_name="typerelation",
            name="no_damage_to",
        ),
        migrations.AddField(
            model_name="typerelation",
            name="double_damage_from",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typerelation",
            name="double_damage_to",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typerelation",
            name="half_damage_from",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typerelation",
            name="half_damage_to",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typerelation",
            name="no_damage_from",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typerelation",
            name="no_damage_to",
            field=models.TextField(blank=True),
        ),
    ]
