# Generated by Django 5.2.6 on 2025-11-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poke_types", "0002_remove_pokemontype_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemontype",
            options={"ordering": ["type_id"]},
        ),
    ]
