# Generated by Django 5.2.6 on 2025-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poke_types", "0003_alter_pokemontype_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TypeRelation",
            new_name="TypeDamageRelation",
        ),
    ]
