# Generated by Django 5.2.6 on 2025-11-18 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("move_id", models.IntegerField(null=True, unique=True)),
                ("accuracy", models.IntegerField(blank=True, null=True)),
                ("power", models.IntegerField(blank=True, null=True)),
                ("pp", models.IntegerField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("effect_chance", models.IntegerField(blank=True, null=True)),
                ("damage_class", models.CharField(blank=True, max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("generation", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("ailment", models.CharField(blank=True, max_length=100)),
                ("ailment_chance", models.IntegerField(blank=True, null=True)),
                ("short_effect", models.TextField(blank=True)),
                ("effect", models.TextField(blank=True)),
                ("flavor_text", models.TextField(blank=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="pokemon_moves", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["move_id"],
            },
        ),
    ]
