# Generated by Django 5.2.6 on 2025-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonability",
            name="accuracy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="ailment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="ailment_chance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="damage_class",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="effect",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="effect_chance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="flavor_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="generation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="power",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="pp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="short_effect",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
