# Generated by Django 5.2.6 on 2025-11-14 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0002_pokemonability_accuracy_pokemonability_ailment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonability",
            name="allowed_users",
            field=models.ManyToManyField(
                related_name="pokemon_moves", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
