# Generated by Django 5.2.6 on 2025-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0003_pokemonability_allowed_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonability",
            name="move_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
