# Generated by Django 5.2.6 on 2025-11-18 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemonability",
            options={"ordering": ["ability_id"]},
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="ability_id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="allowed_users",
            field=models.ManyToManyField(
                related_name="pokemon_ability", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="effect_entries",
            field=models.TextField(
                blank=True, help_text="Localized effects (dicts)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="flavor_text_entries",
            field=models.TextField(
                blank=True, help_text="Localized flavor texts (dicts)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="generation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="is_main_series",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="name",
            field=models.CharField(
                default="default_ability", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="names",
            field=models.TextField(
                blank=True, help_text="List of localized names (dicts)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="pokemons",
            field=models.TextField(
                blank=True,
                help_text="List of Pokémon names or IDs that can have this ability",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pokemonability",
            name="slot",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
