# Generated by Django 5.2.6 on 2025-11-18 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abilities", "0002_alter_pokemonability_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemonability",
            name="is_hidden",
        ),
        migrations.RemoveField(
            model_name="pokemonability",
            name="slot",
        ),
    ]
