# Generated by Django 5.2.6 on 2025-11-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("abilities", "0001_initial"),
        ("moves", "0001_initial"),
        ("poke_types", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("base_experience", models.IntegerField()),
                (
                    "sprite_front_default",
                    models.ImageField(
                        blank=True, null=True, upload_to="pokemon_sprites/"
                    ),
                ),
                (
                    "sprite_front_shiny",
                    models.ImageField(
                        blank=True, null=True, upload_to="pokemon_sprites/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="pokemons", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["pokemon_id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonAbilitiesRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abilities.pokemonability",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ability_relations",
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "ordering": ["slot", "is_hidden"],
                "unique_together": {("pokemon", "ability", "slot")},
            },
        ),
        migrations.CreateModel(
            name="PokemonMoveRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("slot", models.IntegerField()),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moves.pokemonmove",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_relations",
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "ordering": ["slot", "is_hidden"],
                "unique_together": {("pokemon", "move", "slot")},
            },
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=50)),
                ("base_stat", models.IntegerField()),
                ("effort", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "unique_together": {("pokemon", "stat_name")},
            },
        ),
        migrations.CreateModel(
            name="PokemonTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_relations",
                        to="pokemons.pokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poke_types.pokemontype",
                    ),
                ),
            ],
            options={
                "ordering": ["slot"],
                "unique_together": {("pokemon", "type", "slot")},
            },
        ),
    ]
