# Generated by Django 5.2.6 on 2025-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="moves",
            field=models.CharField(null=True),
        ),
    ]
