# Generated by Django 5.2.6 on 2025-09-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
                ("base_experience", models.IntegerField()),
                ("sprite_front_default", models.URLField(max_length=500)),
                ("sprite_front_shiny", models.URLField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pokemon_id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PokemonAbilityRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("slot", models.IntegerField()),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemonability",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ability_relations",
                        to="pokemons.pokemon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=50)),
                ("base_stat", models.IntegerField()),
                ("effort", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="pokemons.pokemon",
                    ),
                ),
            ],
            options={
                "unique_together": {("pokemon", "stat_name")},
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PokemonTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_relations",
                        to="pokemons.pokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemons.pokemontype",
                    ),
                ),
            ],
            options={
                "ordering": ["slot"],
                "unique_together": {("pokemon", "slot")},
            },
        ),
        migrations.DeleteModel(
            name="pokemonTest",
        ),
    ]
