# Generated by Django 5.2.6 on 2025-09-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0002_pokemon_pokemonability_pokemonabilityrelation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="width",
            new_name="weight",
        ),
    ]
