# Generated by Django 5.2.6 on 2025-11-18 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abilities", "0002_alter_pokemonability_options_and_more"),
        ("pokemons", "0002_pokemon_moves"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PokemonAbilitiesRelation",
            new_name="PokemonAbilityRelation",
        ),
    ]
