# Generated by Django 5.2.6 on 2025-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0003_rename_width_pokemon_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="sprite_front_default",
            field=models.ImageField(
                blank=True, null=True, upload_to="pokemon_sprites/"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="sprite_front_shiny",
            field=models.ImageField(
                blank=True, null=True, upload_to="pokemon_sprites/"
            ),
        ),
    ]
