# Generated by Django 5.2.6 on 2025-10-03 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0004_alter_pokemon_sprite_front_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemonabilityrelation",
            options={"ordering": ["slot", "is_hidden"]},
        ),
        migrations.AddField(
            model_name="pokemon",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="pokemon_id",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="pokemon",
            unique_together={("user", "pokemon_id")},
        ),
        migrations.AlterUniqueTogether(
            name="pokemonabilityrelation",
            unique_together={("pokemon", "ability", "slot")},
        ),
        migrations.AlterUniqueTogether(
            name="pokemontyperelation",
            unique_together={("pokemon", "type", "slot")},
        ),
    ]
