# Generated by Django 5.2.6 on 2025-10-03 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0005_alter_pokemonabilityrelation_options_pokemon_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pokemon",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="allowed_users",
            field=models.ManyToManyField(
                related_name="pokemons", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="pokemon_id",
            field=models.IntegerField(unique=True),
        ),
    ]
