# Generated by Django 5.2.6 on 2025-10-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemons",
            "0006_alter_pokemon_unique_together_pokemon_allowed_users_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="user",
        ),
    ]
