# Generated by Django 5.2.6 on 2025-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0007_remove_pokemon_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="location_area_encounters",
            field=models.CharField(null=True),
        ),
    ]
