# Generated by Django 5.2.6 on 2025-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0008_pokemon_location_area_encounters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="location_area_encounters",
        ),
    ]
