# Generated by Django 5.2.6 on 2025-11-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0001_initial"),
        ("poke_types", "0001_initial"),
        ("pokemons", "0009_remove_pokemon_location_area_encounters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonabilityrelation",
            name="ability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="moves.pokemonability"
            ),
        ),
        migrations.AlterField(
            model_name="pokemontyperelation",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="poke_types.pokemontype"
            ),
        ),
        migrations.DeleteModel(
            name="PokemonAbility",
        ),
        migrations.DeleteModel(
            name="PokemonType",
        ),
    ]
