# Generated by Django 5.2.6 on 2025-11-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areas", models.TextField(blank=True)),
                ("game_indices", models.TextField(blank=True)),
                ("location_id", models.IntegerField(unique=True)),
                ("location_name", models.TextField()),
                ("region_name", models.TextField(blank=True)),
            ],
        ),
    ]
