# Generated by Django 5.2.6 on 2025-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_allowed_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="internal_location_name",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
