# Generated by Django 5.2.6 on 2025-12-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_location_internal_location_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encounter_method_rates", models.TextField(blank=True)),
                ("area_id", models.IntegerField(unique=True)),
                ("internal_area_name", models.CharField(max_length=200)),
                ("area_name", models.CharField(max_length=200)),
                ("pokemon_encounters", models.TextField(blank=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        related_name="areas", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
        ),
    ]
