# Generated by Django 5.2.6 on 2025-12-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_area"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["area_id"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["location_id"]},
        ),
    ]
